### ISSUE TITLE
Database Constraints: Users

### ISSUE THREAD

**Issue by vigonotion** [vigonotion/databases-final-project#1]
Users and/or cards with a purchased amount higher than zero cannot be deleted

**Comment by Vanman007** [comment]
We made TInvoice_line prodcut_no as a foreign key to TProduct product_no and there by set
a constraint so that a purchased product cannot be deleted

We made Invoice cCredit_card_no as a foreign key to TCreditCard cCredit_card_no and there by set a
constraint so that a used credit card (any used credit card is a value over 0) in Invoice cannot be deleted and like wise the user has reference to credit card and therefore cannot be deleted as well
